stages:
  - ci
  - sonarcloud
  - trivy_scan
  - docker_push

variables:
  DOCKER_USERNAME: "${DOCKER_USERNAME}"
  DOCKER_PASSWORD: "${DOCKER_PASSWORD}"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

ci_job:
  stage: ci
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm test -- --passWithNoTests
    - npm run build
    - cd ../backend
    - npm install
    - npm run build

sonarcloud_job:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - main
    - merge_requests

trivy_scan_job:
  stage: trivy_scan
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache wget
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.tar.gz
    - tar zxvf trivy_0.64.1_Linux-64bit.tar.gz
    - mv trivy /usr/local/bin/
    - docker build -t backend-img ./backend
    - docker build -t frontend-img ./frontend
    - mkdir -p trivy-reports
    - trivy image backend-img > trivy-reports/backend-report.txt
    - trivy image frontend-img > trivy-reports/frontend-report.txt
    - echo "Trivy scan completed"
  artifacts:
    paths:
      - trivy-reports/

docker_push_job:
  stage: docker_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/todo-app-backend:latest ./backend
    - docker build -t $DOCKER_USERNAME/todo-app-frontend:latest ./frontend
    - docker push $DOCKER_USERNAME/todo-app-backend:latest
    - docker push $DOCKER_USERNAME/todo-app-frontend:latest
