version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network
    restart: always

  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8000
    dns:
      - 8.8.8.8
    networks:
      - todo-network
    restart: always

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network
    restart: always

  
volumes:
  mongo_data:
    driver: local
 

networks:
  todo-network:
    driver: bridge
