apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todo-app
spec:
  selector:
    app: backend
  ports:
    - port: 8080            # Ce que les autres services appellent
      targetPort: 8000      # Ce que ton container écoute réellement
  type: ClusterIP